package hu.nevermind.utils

import kotlinext.js.jsObject


fun jsStyle(body: Style.()->Unit): Style {
    return jsObject {
        body()
    }
}

operator fun Style.plus(other: Style): Style {
    val a = this
    val b = other
    return js("Object.assign(a, b)")
}

interface Style {
    var alignContent: Any
    var alignItems: Any
    var alignSelf: Any
    var all: Any
    var animation: Any
    var animationDelay: Any
    var animationDirection: Any
    var animationDuration: Any
    var animationFillMode: Any
    var animationIterationCount: Any
    var animationName: Any
    var animationPlayState: Any
    var animationTimingFunction: Any
    var backfaceVisibility: Any
    var background: Any
    var backgroundAttachment: Any
    var backgroundBlendMode: Any
    var backgroundClip: Any
    var backgroundColor: Any
    var backgroundImage: Any
    var backgroundOrigin: Any
    var backgroundPosition: Any
    var backgroundRepeat: Any
    var backgroundSize: Any
    var border: Any
    var borderBottom: Any
    var borderBottomColor: Any
    var borderBottomLeftRadius: Any
    var borderBottomRightRadius: Any
    var borderBottomStyle: Any
    var borderBottomWidth: Any
    var borderCollapse: Any
    var borderColor: Any
    var borderImage: Any
    var borderImageOutset: Any
    var borderImageRepeat: Any
    var borderImageSlice: Any
    var borderImageSource: Any
    var borderImageWidth: Any
    var borderLeft: Any
    var borderLeftColor: Any
    var borderLeftStyle: Any
    var borderLeftWidth: Any
    var borderRadius: Any
    var borderRight: Any
    var borderRightColor: Any
    var borderRightStyle: Any
    var borderRightWidth: Any
    var borderSpacing: Any
    var borderStyle: Any
    var borderTop: Any
    var borderTopColor: Any
    var borderTopLeftRadius: Any
    var borderTopRightRadius: Any
    var borderTopStyle: Any
    var borderTopWidth: Any
    var borderWidth: Any
    var bottom: Any
    var boxDecorationBreak: Any
    var boxShadow: Any
    var boxSizing: Any
    var breakAfter: Any
    var breakBefore: Any
    var breakInside: Any
    var captionSide: Any
    var caretColor: Any
    var clear: Any
    var clip: Any
    var color: Any
    var columnCount: Any
    var columnFill: Any
    var columnGap: Any
    var columnRule: Any
    var columnRuleColor: Any
    var columnRuleStyle: Any
    var columnRuleWidth: Any
    var columnSpan: Any
    var columnWidth: Any
    var columns: Any
    var content: Any
    var counterIncrement: Any
    var counterReset: Any
    var cursor: Any
    var direction: Any
    var display: Any
    var emptyCells: Any
    var filter: Any
    var flex: Any
    var flexBasis: Any
    var flexDirection: Any
    var flexFlow: Any
    var flexGrow: Any
    var flexShrink: Any
    var flexWrap: Any
    var float: Any
    var font: Any
    var fontFamily: Any
    var fontFeatureSettings: Any
    var fontKerning: Any
    var fontLanguageOverride: Any
    var fontSize: Any
    var fontSizeAdjust: Any
    var fontStretch: Any
    var fontStyle: Any
    var fontSynthesis: Any
    var fontVariant: Any
    var fontVariantAlternates: Any
    var fontVariantCaps: Any
    var fontVariantEastAsian: Any
    var fontVariantLigatures: Any
    var fontVariantNumeric: Any
    var fontVariantPosition: Any
    var fontWeight: Any
    var grid: Any
    var gridArea: Any
    var gridAutoColumns: Any
    var gridAutoFlow: Any
    var gridAutoRows: Any
    var gridColumn: Any
    var gridColumnEnd: Any
    var gridColumnGap: Any
    var gridColumnStart: Any
    var gridGap: Any
    var gridRow: Any
    var gridRowEnd: Any
    var gridRowGap: Any
    var gridRowStart: Any
    var gridTemplate: Any
    var gridTemplateAreas: Any
    var gridTemplateColumns: Any
    var gridTemplateRows: Any
    var hangingPunctuation: Any
    var height: Any
    var hyphens: Any
    var imageRendering: Any
    var isolation: Any
    var justifyContent: Any
    var left: Any
    var letterSpacing: Any
    var lineBreak: Any
    var lineHeight: Any
    var listStyle: Any
    var listStyleImage: Any
    var listStylePosition: Any
    var listStyleType: Any
    var margin: Any
    var marginBottom: Any
    var marginLeft: Any
    var marginRight: Any
    var marginTop: Any
    var maxHeight: Any
    var maxWidth: Any
    var minHeight: Any
    var minWidth: Any
    var mixBlendMode: Any
    var objectFit: Any
    var objectPosition: Any
    var opacity: Any
    var order: Any
    var orphans: Any
    var outline: Any
    var outlineColor: Any
    var outlineOffset: Any
    var outlineStyle: Any
    var outlineWidth: Any
    var overflow: Any
    var Specifies: Any
    var overflowWrap: Any
    var overflowX: Any
    var overflowY: Any
    var padding: Any
    var paddingBottom: Any
    var paddingLeft: Any
    var paddingRight: Any
    var paddingTop: Any
    var pageBreakAfter: Any
    var pageBreakBefore: Any
    var pageBreakInside: Any
    var perspective: Any
    var perspectiveOrigin: Any
    var pointerEvents: Any
    var position: Any
    var quotes: Any
    var resize: Any
    var right: Any
    var tabSize: Any
    var tableLayout: Any
    var textAlign: Any
    var textAlignLast: Any
    var textCombineUpright: Any
    var textDecoration: Any
    var textDecorationColor: Any
    var textDecorationLine: Any
    var textDecorationStyle: Any
    var textIndent: Any
    var textJustify: Any
    var textOrientation: Any
    var textOverflow: Any
    var textShadow: Any
    var textTransform: Any
    var textUnderlinePosition: Any
    var top: Any
    var transform: Any
    var transformOrigin: Any
    var transformStyle: Any
    var transition: Any
    var transitionDelay: Any
    var transitionDuration: Any
    var transitionProperty: Any
    var transitionTimingFunction: Any
    var unicodeBidi: Any
    var userSelect: Any
    var verticalAlign: Any
    var visibility: Any
    var whiteSpace: Any
    var widows: Any
    var width: Any
    var wordBreak: Any
    var wordSpacing: Any
    var wordWrap: Any
    var writingMode: Any
    var zIndex: Any
}